# fly.toml file generated for odontonet on 2023-03-16T11:18:47-04:00

app = "odontonet"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "scl"
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[env]
  APP_ENV = "production"
  APP_NAME = "OdontoNet"
  DB_CONNECTION = "pgsql"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  MAIL_ENCRYPTION = "STARTTLS"
  MAIL_FROM_ADDRESS = "rodrigo.gandarillas.heredia@outlook.com"
  MAIL_FROM_NAME = "OdontoNet"
  MAIL_HOST = "smtp-mail.outlook.com"
  MAIL_MAILER = "smtp"
  MAIL_PASSWORD = "rodri170495"
  MAIL_PORT = "587"
  MAIL_USERNAME = "rodrigo.gandarillas.heredia@outlook.com"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
